### ISSUE TITLE
mpienv add error 

### ISSUE THREAD

**Issue by shu65** [keisukefukuda/mpienv#47]
When I used mpienv add command to add mpi path by the following command, mpienv output error.
```
$ mpienv add /usr/bin/
Traceback (most recent call last):
  File "/home/ssuzuki/.mpienv/bin/add.py", line 22, in <module>
    main()
  File "/home/ssuzuki/.mpienv/bin/add.py", line 18, in main
    manager.add(args.path, args.name)
  File "/home/ssuzuki/.mpienv/common.py", line 304, in add
    name = info['default_name']
KeyError: 'default_name'
```

How can I solve it?

**Comment by keisukefukuda** [comment]
I think it's a bug... I will fix it soon. Thanks!

**Comment by keisukefukuda** [comment]
Updated. Please `pull` the latest version and check if works.

**Comment by shu65** [comment]
I checked it. I can use this command. Thanks
